books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^books/$', views.index, name='index'),
    url(r'^genres/json/$', views.GenreList.as_view(), name="genre-json"),
    url(r'^books/json/$', views.BookList.as_view(), name="book-index-json"),
    url(r'authors/json/$', views.AuthorList.as_view(), name='author-index-json'),
    url(r'authors/(?P<pk>\d+)/json/$', views.AuthorDetail.as_view(), name='author-detail-json'),
    url(r'^books/(?P<comic_book_id>\d+)/$', views.detail, name='detail'),
    url(r'^books/(?P<pk>\d+)/json/$', views.BookDetail.as_view(), name="book-detail-json"),
    url(r'^books/new/$', views.new, name='new'),
    url(r'^books/(?P<comic_book_id>\d+)/reviews', views.BookReviewList.as_view(), name='book-reviews'),
]

cbook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('books.urls', namespace='books')),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

books/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)

class Author(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class ComicBook(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    author = models.ForeignKey(Author)
    genres = models.ManyToManyField(Genre)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Review(models.Model):
    content = models.TextField()
    rating = models.IntegerField()
    comic_book = models.ForeignKey(ComicBook)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

users/models.py
from django.db import models

# Create your models here.

books/forms.py
from django import forms
from .models import ComicBook, Author

class ComicBookForm(forms.ModelForm):
    class Meta:
        model = ComicBook
        fields = ['title', 'description', 'author',]
        labels = {'title': 'title', 'description': 'description', 'author': 'author'}

books/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from rest_framework import generics

from .models import Author, Genre, ComicBook, Review
from .serializers import AuthorSerializer, GenreSerializer, ComicBookSerializer, ReviewSerializer
from .forms import ComicBookForm
# Create your views here.

def home(request):
    return render(request, 'books/home.html')

def index(request):
    context = {'books': ComicBook.objects.all()}
    return render(request, 'books/index.html', context)

def detail(request, comic_book_id):
    book = ComicBook.objects.get(id=comic_book_id)
    context = {'book': book}
    return render(request, 'books/detail.html', context)

@login_required
def new(request):
    if request.method != 'POST':
        form = ComicBookForm()
    else:
        form = ComicBookForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('books:index'))

    context = {'form': form}
    return render(request, 'books/new.html', context)

class BookList(generics.ListCreateAPIView):
    queryset = ComicBook.objects.all()
    serializer_class = ComicBookSerializer

class GenreList(generics.ListCreateAPIView):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer

class BookDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = ComicBook.objects.all()
    serializer_class = ComicBookSerializer

class AuthorList(generics.ListCreateAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

class AuthorDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

class BookReviewList(generics.ListCreateAPIView):
    model = Review
    queryset = Review.objects.all()
    serializer_class = ReviewSerializer

    def get_queryset(self):
        queryset = super(BookReviewList, self).get_queryset()
        return queryset.filter(comic_book__pk = self.kwargs.get('comic_book_id'))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout

# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('books:index'))

books/templates/books/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'books/stylesheets/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'books/stylesheets/style.css' %}" />

<script src="{% static 'books/javascripts/jquery.min.js' %}"></script>
<script src="{% static 'books/javascripts/bootstrap.min.js' %}"></script>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="#">CBook-v2</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
		    <li><a href="{% url 'books:index' %}">All Comic Books</a></li>
		    <li><a href="{% url 'books:new' %}">Add a Comic Book</a></li>
		    <li><a href="/authors">Authors</a></li>
		    <li><a href="/artists">Artists</a></li>
		    <li><a href="/genres">Genres</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        {% if user.is_authenticated %}
            <li>Hello, {{ user.username }}</li><br />
            <a href="{% url 'users:logout' %}">Log out </a>
        {% else %}
            <li><a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block content %}

{% endblock content %}

books/templates/books/detail.html
{% extends 'books/base.html' %}

{% block content %}

<div class="display-box">
		<h2>{{ book.title }} by {{ book.author }}</h2>
		<p>{{ book.description }}</p>
</div>

{% endblock content %}

books/templates/books/home.html
{% extends 'books/base.html' %}

{% block content %}
<h1>Welcome! Read some reviews and add some of your own!</h1>

{% endblock content %}

books/templates/books/index.html
{% extends 'books/base.html' %}
{% block content %}
		<h1>All Comic Books</h1>

		{% for book in books %}
		<a href="{% url 'books:detail' book.id %}">
			<div class="display-box">
				<h2>{{ book.title }} by {{ book.author }}</h2>
				<p>{{ book.description }}</p>
			</div>
		</a>
		{% endfor %}
{% endblock content %}

books/templates/books/new.html
{% extends 'books/base.html' %}

{% block content %}

		<p>Add a new comic book:</p>

		<form action="{% url 'books:new' %}" method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button name="submit">Create book</button>
		</form>
{% endblock content %}

frontend/js/templates/books.html
<h1>You'll see a list of books here some day</h1>

<ul>
		<li ng-repeat="book in bookCtrl.bookData">
				<p>{{ book.pk + ": " + book.title }}<p>
		</li>
</p>

frontend/js/templates/books/list.html
<h1>You'll see a list of books here some day</h1>

<ul>
		<li ng-repeat="book in bookCtrl.bookData">
				<a href="" ui-sref="book({id: book.pk})"><p>{{ book.pk + ": " + book.title }}</p></a>
		</li>
</ul>

<p><a href="" ui-sref="books.new">Add a book</a></p>

<div ui-view></div>

frontend/js/templates/books/new.html
<h3>New book preview:</h3>

<p>{{ (bookCtrl.bookData.length + 1) + ": " + bookCtrl.newBook.title }}</p>
<p>Description: {{ bookCtrl.newBook.description }}</p>
<p>Author: {{ bookCtrl.newBook.author }}</p>

<form name="form" ng-submit="bookCtrl.addBook()">
		<label>Title:</label>
		<input ng-model="bookCtrl.newBook.title"></input><br />

		<label>Description:</label>
		<input ng-model="bookCtrl.newBook.description"></input><br />

		<label>Select some Genres:</label>
		<select ng-options="genre.name as genre.name for genre in bookCtrl.genreData" ng-model="bookCtrl.newBook.genres" multiple></select><br />

		<label>Or create a new one:</label>
		<input ng-model="bookCtrl.newBook.newGenre"></input><br />

		<label> Author:</label>
		<input ng-model="bookCtrl.newBook.author"></input><br />

		<input type="submit" value="Add book">
</form>

<h1>{{ bookCtrl.genreData }}</h1>

frontend/js/templates/books/show.html
<h1>{{ bookCtrl.bookData.title }} by {{ bookCtrl.bookData.author }}</h1>
<h3>Genres:
	<ul>
		<li ng-repeat="genre in bookCtrl.bookData.genres">{{ genre }}</li>
	</ul>
<p>{{ bookCtrl.bookData.description }}</p>

frontend/js/templates/home.html
<h1><strong>This is the home page lolololol</strong></h1>

users/templates/users/login.html
{% extends 'books/base.html' %}


{% block content %}
		{% if form.errors %}
				<p>Your username and password didn't match. Please try again.</p>
		{% endif %}

		<form method="post" action="{% url 'users:login' %}">
				{% csrf_token %}
				{{ form.as_p }}

				<button name="submit">Log in</button>

				<input type="hidden" name="next" value="{% url 'books:index' %}" />
		</form>
{% endblock content %}